In [17]:
import numpy as np
import torch

In [18]:
a = torch.tensor(np.array(range(120)).reshape(5, 2, 4, 3))

In [19]:
a

tensor([[[[  0,   1,   2],
          [  3,   4,   5],
          [  6,   7,   8],
          [  9,  10,  11]],

         [[ 12,  13,  14],
          [ 15,  16,  17],
          [ 18,  19,  20],
          [ 21,  22,  23]]],


        [[[ 24,  25,  26],
          [ 27,  28,  29],
          [ 30,  31,  32],
          [ 33,  34,  35]],

         [[ 36,  37,  38],
          [ 39,  40,  41],
          [ 42,  43,  44],
          [ 45,  46,  47]]],


        [[[ 48,  49,  50],
          [ 51,  52,  53],
          [ 54,  55,  56],
          [ 57,  58,  59]],

         [[ 60,  61,  62],
          [ 63,  64,  65],
          [ 66,  67,  68],
          [ 69,  70,  71]]],


        [[[ 72,  73,  74],
          [ 75,  76,  77],
          [ 78,  79,  80],
          [ 81,  82,  83]],

         [[ 84,  85,  86],
          [ 87,  88,  89],
          [ 90,  91,  92],
          [ 93,  94,  95]]],


        [[[ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104],
          [105, 106, 107]],

  

In [20]:
b = a.permute((0, 3, 1, 2))
b

tensor([[[[  0,   3,   6,   9],
          [ 12,  15,  18,  21]],

         [[  1,   4,   7,  10],
          [ 13,  16,  19,  22]],

         [[  2,   5,   8,  11],
          [ 14,  17,  20,  23]]],


        [[[ 24,  27,  30,  33],
          [ 36,  39,  42,  45]],

         [[ 25,  28,  31,  34],
          [ 37,  40,  43,  46]],

         [[ 26,  29,  32,  35],
          [ 38,  41,  44,  47]]],


        [[[ 48,  51,  54,  57],
          [ 60,  63,  66,  69]],

         [[ 49,  52,  55,  58],
          [ 61,  64,  67,  70]],

         [[ 50,  53,  56,  59],
          [ 62,  65,  68,  71]]],


        [[[ 72,  75,  78,  81],
          [ 84,  87,  90,  93]],

         [[ 73,  76,  79,  82],
          [ 85,  88,  91,  94]],

         [[ 74,  77,  80,  83],
          [ 86,  89,  92,  95]]],


        [[[ 96,  99, 102, 105],
          [108, 111, 114, 117]],

         [[ 97, 100, 103, 106],
          [109, 112, 115, 118]],

         [[ 98, 101, 104, 107],
          [110, 113, 116, 119]]]])

In [24]:
# 5,2,4,3
# l.h.w.c
a[0,:,:,:]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [23]:
# 5,3,4,2
# l.c.h.w
b[0,:,:,:]

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]])

In [30]:
a = torch.tensor(np.array(range(120)).reshape(5, 2, 4, 3))
a[0]

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]])

In [32]:
b = a.permute((0, 3, 1, 2)).reshape((3*5, 2, 4))
b[0:3,:,:]

tensor([[[ 0,  3,  6,  9],
         [12, 15, 18, 21]],

        [[ 1,  4,  7, 10],
         [13, 16, 19, 22]],

        [[ 2,  5,  8, 11],
         [14, 17, 20, 23]]])